# Generated by Django 6.0.2 on 2026-02-05 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the field (e.g., 'North Field A')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Geographic location or coordinates", max_length=300
                    ),
                ),
                (
                    "size_acres",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Field size in acres",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                            ("chalky", "Chalky"),
                        ],
                        help_text="Primary soil classification",
                        max_length=50,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("drip", "Drip Irrigation"),
                            ("sprinkler", "Sprinkler"),
                            ("flood", "Flood/Surface"),
                            ("furrow", "Furrow"),
                            ("rainfed", "Rainfed"),
                            ("other", "Other"),
                        ],
                        help_text="Irrigation method used",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the field",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CropHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(
                        help_text="Name of the crop (e.g., 'Wheat', 'Corn', 'Soybeans')",
                        max_length=200,
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True,
                        help_text="Specific variety or cultivar",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "planting_date",
                    models.DateField(help_text="Date when the crop was planted"),
                ),
                (
                    "harvest_date",
                    models.DateField(help_text="Date when the crop was harvested"),
                ),
                (
                    "yield_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yield in kg per acre",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fertilizer_used",
                    models.CharField(
                        blank=True,
                        help_text="Fertilizers applied during growth",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "pesticide_used",
                    models.CharField(
                        blank=True,
                        help_text="Pesticides or herbicides applied",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "weather_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Notable weather conditions during growing season",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional observations or notes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field where the crop was grown",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_histories",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop History",
                "verbose_name_plural": "Crop Histories",
                "ordering": ["-harvest_date"],
            },
        ),
    ]
