# Generated by Django 6.0.2 on 2026-02-06 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("expense", "Expense"),
                            ("income", "Income"),
                            ("investment", "Investment"),
                        ],
                        help_text="Type of financial transaction",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seeds", "Seeds & Planting Material"),
                            ("fertilizer", "Fertilizer"),
                            ("pesticides", "Pesticides & Herbicides"),
                            ("irrigation", "Irrigation & Water"),
                            ("labor", "Labor Costs"),
                            ("equipment", "Equipment & Machinery"),
                            ("fuel", "Fuel & Energy"),
                            ("maintenance", "Maintenance & Repairs"),
                            ("storage", "Storage & Warehousing"),
                            ("transportation", "Transportation"),
                            ("consulting", "Consulting & Services"),
                            ("insurance", "Insurance"),
                            ("taxes", "Taxes & Fees"),
                            ("other_expense", "Other Expenses"),
                            ("crop_sales", "Crop Sales"),
                            ("subsidies", "Government Subsidies"),
                            ("grants", "Grants"),
                            ("other_income", "Other Income"),
                            ("land", "Land Purchase"),
                            ("infrastructure", "Infrastructure"),
                            ("equipment_purchase", "Equipment Purchase"),
                            ("other_investment", "Other Investments"),
                        ],
                        help_text="Transaction category",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount in local currency",
                        max_digits=12,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Transaction date"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the transaction"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantity (kg, liters, units, etc.)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (kg, liters, bags, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "vendor_buyer",
                    models.CharField(
                        blank=True,
                        help_text="Vendor (for expenses) or Buyer (for income)",
                        max_length=200,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Invoice or receipt number",
                        max_length=100,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("check", "Check"),
                            ("credit_card", "Credit Card"),
                            ("mobile_payment", "Mobile Payment"),
                            ("other", "Other"),
                        ],
                        help_text="Payment method used",
                        max_length=50,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Is this a recurring transaction?"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop_history",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific crop harvest related to this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_records",
                        to="fields.crophistory",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        help_text="Field related to this transaction (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_records",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Record",
                "verbose_name_plural": "Financial Records",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial_summary", "Financial Summary"),
                            ("yield_analysis", "Yield Analysis"),
                            ("soil_health", "Soil Health Report"),
                            ("rotation_performance", "Rotation Performance"),
                            ("field_comparison", "Field Comparison"),
                            ("seasonal_overview", "Seasonal Overview"),
                            ("profitability", "Profitability Analysis"),
                            ("custom", "Custom Report"),
                        ],
                        help_text="Type of report",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(help_text="Report title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Report description"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Report period start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Report period end date", null=True
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON data containing report metrics and data",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Executive summary of the report"
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        blank=True,
                        help_text="Person or system that generated the report",
                        max_length=100,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to exported PDF/CSV file",
                        max_length=500,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Is this report published/finalized?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fields_included",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Fields included in this report",
                        related_name="reports",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YieldForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(help_text="Crop being forecasted", max_length=100),
                ),
                (
                    "forecast_year",
                    models.IntegerField(help_text="Year of the forecast"),
                ),
                (
                    "planting_season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("fall", "Fall"),
                            ("winter", "Winter"),
                        ],
                        help_text="Planned planting season",
                        max_length=20,
                    ),
                ),
                (
                    "predicted_yield_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Predicted yield in kg",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence_level",
                    models.IntegerField(
                        default=70, help_text="Forecast confidence level (0-100%)"
                    ),
                ),
                (
                    "prediction_method",
                    models.CharField(
                        choices=[
                            ("historical_average", "Historical Average"),
                            ("trend_analysis", "Trend Analysis"),
                            ("ml_model", "Machine Learning Model"),
                            ("expert_estimate", "Expert Estimate"),
                            ("hybrid", "Hybrid Method"),
                        ],
                        default="historical_average",
                        help_text="Method used for prediction",
                        max_length=50,
                    ),
                ),
                (
                    "factors_considered",
                    models.JSONField(
                        default=dict,
                        help_text="JSON data with factors considered in prediction",
                    ),
                ),
                (
                    "actual_yield_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual yield achieved (filled after harvest)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "variance_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Variance between predicted and actual",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the forecast"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_forecasts",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yield Forecast",
                "verbose_name_plural": "Yield Forecasts",
                "ordering": ["-forecast_year", "field"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("yield_efficiency", "Yield Efficiency"),
                            ("soil_health_score", "Soil Health Score"),
                            ("profitability", "Profitability"),
                            ("resource_efficiency", "Resource Efficiency"),
                            ("sustainability_score", "Sustainability Score"),
                            ("crop_diversity", "Crop Diversity"),
                            ("rotation_adherence", "Rotation Plan Adherence"),
                            ("weather_resilience", "Weather Resilience"),
                            ("pest_resistance", "Pest Resistance"),
                            ("nutrient_balance", "Nutrient Balance"),
                        ],
                        help_text="Type of performance metric",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Performance score (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "measurement_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of measurement",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year of measurement")),
                (
                    "month",
                    models.IntegerField(
                        blank=True, help_text="Month of measurement (1-12)", null=True
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data with calculation breakdown",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this metric"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Metric",
                "verbose_name_plural": "Performance Metrics",
                "ordering": ["-measurement_date", "field"],
                "unique_together": {("field", "metric_type", "measurement_date")},
            },
        ),
    ]
