# Generated by Django 6.0.2 on 2026-02-05 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("planting", "Planting"),
                            ("irrigation", "Irrigation"),
                            ("fertilization", "Fertilization"),
                            ("pest_control", "Pest Control"),
                            ("harvesting", "Harvesting"),
                            ("soil_preparation", "Soil Preparation"),
                            ("pruning", "Pruning"),
                            ("other", "Other"),
                        ],
                        help_text="Type of farming activity",
                        max_length=20,
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(
                        help_text="Crop name for this activity", max_length=200
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True,
                        help_text="Crop variety (optional)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(help_text="Scheduled date for activity"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="End date for multi-day activities (optional)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="planned",
                        help_text="Current status of activity",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the activity",
                        null=True,
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated duration in days",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "recommended_temperature_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum recommended temperature (°C)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_temperature_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum recommended temperature (°C)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "send_reminder",
                    models.BooleanField(
                        default=True, help_text="Send reminder notification"
                    ),
                ),
                (
                    "reminder_days_before",
                    models.IntegerField(
                        default=3,
                        help_text="Days before event to send reminder",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop_history",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked crop history record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="fields.crophistory",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field for this activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Calendar Event",
                "verbose_name_plural": "Crop Calendar Events",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="CropRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_crop",
                    models.CharField(help_text="Recommended crop name", max_length=200),
                ),
                (
                    "recommended_variety",
                    models.CharField(
                        blank=True,
                        help_text="Recommended variety",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "planting_season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("fall", "Fall"),
                            ("winter", "Winter"),
                            ("year_round", "Year Round"),
                        ],
                        help_text="Best planting season",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        help_text="Confidence score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(help_text="Why this crop is recommended"),
                ),
                (
                    "expected_yield_range",
                    models.CharField(
                        blank=True,
                        help_text="Expected yield range (e.g., '2000-3000 kg/acre')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ideal_planting_window_start",
                    models.DateField(
                        blank=True, help_text="Ideal planting window start", null=True
                    ),
                ),
                (
                    "ideal_planting_window_end",
                    models.DateField(
                        blank=True, help_text="Ideal planting window end", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field for recommendation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_recommendations",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Recommendation",
                "verbose_name_plural": "Crop Recommendations",
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of weather observation")),
                (
                    "temperature_high",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="High temperature in Celsius",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-50),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "temperature_low",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Low temperature in Celsius",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-50),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "rainfall_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rainfall in millimeters",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "humidity_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Relative humidity percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "wind_speed_kmh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wind speed in km/h",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("partly_cloudy", "Partly Cloudy"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("stormy", "Stormy"),
                            ("foggy", "Foggy"),
                            ("snowy", "Snowy"),
                        ],
                        default="sunny",
                        help_text="General weather condition",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional weather observations",
                        null=True,
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=True,
                        help_text="Whether data was manually entered or from API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field where weather was recorded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "ordering": ["-date"],
                "unique_together": {("field", "date")},
            },
        ),
    ]
