# Generated by Django 6.0.2 on 2026-02-06 05:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RotationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this rotation plan", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of rotation strategy",
                    ),
                ),
                (
                    "start_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "duration_years",
                    models.IntegerField(
                        help_text="Number of years for this rotation cycle (2-10 years)",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "primary_goal",
                    models.CharField(
                        choices=[
                            ("yield_max", "Maximize Yield"),
                            ("soil_health", "Improve Soil Health"),
                            ("pest_control", "Pest and Disease Management"),
                            ("profit_max", "Maximize Profit"),
                            ("sustainability", "Long-term Sustainability"),
                            ("organic", "Organic Certification"),
                        ],
                        default="yield_max",
                        max_length=50,
                    ),
                ),
                (
                    "ai_generated",
                    models.BooleanField(
                        default=False, help_text="Was this plan AI-generated?"
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        default=50,
                        help_text="AI confidence in this rotation plan (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="User who created this plan",
                        max_length=100,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_plans",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rotation Plan",
                "verbose_name_plural": "Rotation Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RotationBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("soil_health", "Soil Health Improvement"),
                            ("pest_control", "Pest and Disease Control"),
                            ("yield_increase", "Yield Increase"),
                            ("nitrogen_fixation", "Nitrogen Fixation"),
                            ("organic_matter", "Organic Matter Increase"),
                            ("erosion_control", "Erosion Control"),
                            ("weed_suppression", "Weed Suppression"),
                            ("water_conservation", "Water Conservation"),
                            ("biodiversity", "Biodiversity Enhancement"),
                            ("profit_increase", "Profit Increase"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the expected benefit"
                    ),
                ),
                (
                    "expected_improvement_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected % improvement (e.g., 15.5 for 15.5% increase)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "actual_improvement_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual % improvement achieved",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "expected_to_manifest_year",
                    models.IntegerField(
                        help_text="Year in rotation when benefit is expected to manifest",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Has this benefit been verified?"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Notes on benefit verification"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="Priority of this benefit (1=low, 10=high)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rotation_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="rotation.rotationplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rotation Benefit",
                "verbose_name_plural": "Rotation Benefits",
                "ordering": ["-priority", "rotation_plan", "expected_to_manifest_year"],
            },
        ),
        migrations.CreateModel(
            name="RotationSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_in_rotation",
                    models.IntegerField(
                        help_text="Year number in the rotation cycle (1, 2, 3, etc.)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(
                        help_text="Name of the crop to plant", max_length=100
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True,
                        help_text="Specific variety/cultivar",
                        max_length=100,
                    ),
                ),
                (
                    "planting_season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("fall", "Fall"),
                            ("winter", "Winter"),
                            ("year_round", "Year Round"),
                        ],
                        default="spring",
                        max_length=20,
                    ),
                ),
                (
                    "expected_planting_month",
                    models.IntegerField(
                        help_text="Month number (1-12) for planting",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "expected_harvest_month",
                    models.IntegerField(
                        help_text="Month number (1-12) for harvest",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "expected_yield_kg_per_acre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected yield in kg per acre",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fertilizer_plan",
                    models.TextField(
                        blank=True, help_text="Fertilization strategy for this crop"
                    ),
                ),
                (
                    "irrigation_plan",
                    models.TextField(
                        blank=True, help_text="Irrigation strategy for this crop"
                    ),
                ),
                (
                    "pest_management_plan",
                    models.TextField(
                        blank=True, help_text="Pest and disease management"
                    ),
                ),
                (
                    "nitrogen_requirement",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("nitrogen_fixing", "Nitrogen Fixing"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "reason_for_selection",
                    models.TextField(
                        blank=True,
                        help_text="Why this crop was chosen for this position in the rotation",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Has this sequence been completed?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actual_crop_history",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to actual crop history record when completed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotation_sequence",
                        to="fields.crophistory",
                    ),
                ),
                (
                    "rotation_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="rotation.rotationplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rotation Sequence",
                "verbose_name_plural": "Rotation Sequences",
                "ordering": ["rotation_plan", "year_in_rotation"],
                "unique_together": {("rotation_plan", "year_in_rotation")},
            },
        ),
    ]
