# Generated by Django 6.0.2 on 2026-02-05 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(help_text="Date when soil analysis was conducted"),
                ),
                (
                    "ph_level",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Soil pH level (0-14 scale)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "organic_matter",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Organic matter percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "nitrogen_ppm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nitrogen content in ppm",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Nitrogen (ppm)",
                    ),
                ),
                (
                    "phosphorus_ppm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Phosphorus content in ppm",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Phosphorus (ppm)",
                    ),
                ),
                (
                    "potassium_ppm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Potassium content in ppm",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Potassium (ppm)",
                    ),
                ),
                (
                    "calcium_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calcium content in ppm",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Calcium (ppm)",
                    ),
                ),
                (
                    "magnesium_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Magnesium content in ppm",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Magnesium (ppm)",
                    ),
                ),
                (
                    "sulfur_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sulfur content in ppm",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Sulfur (ppm)",
                    ),
                ),
                (
                    "cec",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cation Exchange Capacity (meq/100g)",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="CEC",
                    ),
                ),
                (
                    "moisture_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Soil moisture content percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional observations or lab notes",
                        null=True,
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the testing laboratory",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field where soil was analyzed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_analyses",
                        to="fields.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Analysis",
                "verbose_name_plural": "Soil Analyses",
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="NutrientRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nutrient",
                    models.CharField(
                        choices=[
                            ("nitrogen", "Nitrogen"),
                            ("phosphorus", "Phosphorus"),
                            ("potassium", "Potassium"),
                            ("calcium", "Calcium"),
                            ("magnesium", "Magnesium"),
                            ("sulfur", "Sulfur"),
                            ("ph", "pH Adjustment"),
                            ("organic_matter", "Organic Matter"),
                        ],
                        help_text="Nutrient or soil parameter",
                        max_length=50,
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("optimal", "Optimal"),
                        ],
                        help_text="Current level status",
                        max_length=20,
                    ),
                ),
                (
                    "recommended_action",
                    models.TextField(
                        help_text="Recommended action to improve soil health"
                    ),
                ),
                (
                    "application_rate",
                    models.CharField(
                        blank=True,
                        help_text="Recommended application rate (e.g., '50 kg/acre')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="Priority level (1=Low, 10=High)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "soil_analysis",
                    models.ForeignKey(
                        help_text="Related soil analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="soil.soilanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrient Recommendation",
                "verbose_name_plural": "Nutrient Recommendations",
                "ordering": ["-priority", "nutrient"],
            },
        ),
    ]
